name: p2plib
description: 'Tooling for encrypted udp datagram peer to peer communication'
homepage: https://github.com/alexandrim0/p2plib-dart
repository: https://github.com/alexandrim0/p2plib-dart
issue_tracker: https://github.com/alexandrim0/p2plib-dart/issues

topics:
  - p2p
  - web3
  - network

version: 2.3.1

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies: 
  meta: ^1.16.0
  sodium: ^3.4.6
  collection: ^1.17.0

dev_dependencies:
  test: ^1.26.3
  very_good_analysis: ^10.0.0
