name: dart_ipfs
description: A Dart implementation of an IPFS server.
version: 1.0.0 # Initial version
homepage: https://github.com/jxoesneon/IPFS
repository: https://github.com/jxoesneon/IPFS
issue_tracker: https://github.com/jxoesneon/IPFS/issues
license: MIT  # Or your chosen license
publish_to: none

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  catalyst_cose: ^1.0.0

  collection: ^1.19.1
  
  http: ^1.2.2

  fixnum: ^1.1.1

  convert: ^3.1.2

  uuid: ^4.5.1

  # Networking and P2P
  p2plib: ^2.2.2 # Or a suitable libp2p implementation for Dart

  # Cryptography
  crypto: ^3.0.3 # For CID calculation and other cryptographic operations

  # Serialization
  protobuf: ^6.0.0 # Compatible with protoc_plugin 25.x

  # Data Storage
  hive: ^2.2.3 # Local database for persistent storage

  # Logging
  logging: ^1.0.2 # For logging events and debugging

  # Metrics (Optional)
  prometheus_client: ^1.0.0+1 # Metrics library for monitoring

  dart_merkle_lib: ^1.0.1

  multibase: ^1.0.0

  dart_multihash: ^1.0.1
  archive: ^4.0.7
  murmurhash: ^1.0.1

  cbor: ^6.3.3  # Or the latest version

  # lz4: ^0.0.1  # Package not available on pub.dev

  shelf_router: ^1.1.4

  intl: ^0.20.0  # Use the latest stable version

  markdown: ^7.2.2
  synchronized: ^3.3.0+3
  multicast_dns: ^0.3.2+7

  pointycastle: ^4.0.0

  jose: ^0.3.4
  
  mime: ^2.0.0 # For content-type detection in gateway

  yaml: any
  meta: any
  shelf: any
  path: any
  grpc: any
dev_dependencies:
  test: ^1.21.0 # For unit and integration tests
  lints: ^6.0.0 # For code style analysis

# Assets used in the project, such as images or other static files.
assets:
  - lib/assets/logo.svg

# Example entry point for running the application.
example:
  main.dart

# Specify any additional files or directories to include in the package.
include:
  - lib/src/core/
  - lib/src/proto/
