name: dart_ipfs
description: A Dart implementation of an IPFS server.
version: 0.0.1 # Initial version
homepage: https://github.com/jxoesneon/IPFS
repository: https://github.com/jxoesneon/IPFS
issue_tracker: https://github.com/jxoesneon/IPFS/issues
license: MIT  # Or your chosen license
publish_to: none

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  collection: ^1.19.1
  
  http: ^1.2.2

  fixnum: ^1.1.1

  convert: ^3.1.2

  uuid: ^4.5.1

  # Networking and P2P
  p2plib: ^2.2.2 # Or a suitable libp2p implementation for Dart

  # Cryptography
  crypto: ^3.0.2 # For CID calculation and other cryptographic operations

  # Serialization
  protobuf: ^3.1.0 # Efficient serialization format for messages

  # Data Storage
  hive: ^2.2.3 # Local database for persistent storage

  # Logging
  logging: ^1.0.2 # For logging events and debugging

  # Metrics (Optional)
  prometheus_client: ^1.0.0+1 # Metrics library for monitoring

  dart_merkle_lib: ^1.0.1

  multibase: ^1.0.0

  dart_multihash: ^1.0.1
  archive: ^3.6.1
  murmurhash: ^1.0.1

  cbor: ^5.1.0  # Or the latest version

dev_dependencies:
  test: ^1.21.0 # For unit and integration tests
  lints: ^5.0.0 # For code style analysis

# Assets used in the project, such as images or other static files.
assets:
  - lib/assets/logo.svg

# Example entry point for running the application.
example:
  main.dart

# Specify any additional files or directories to include in the package.
include:
  - lib/src/core/
  - lib/src/proto/
